#!/usr/bin/env node
var consts = require('./constants')
var app = require('./app');

app.set('port', process.env.PORT || consts.web.port);

var server = app.listen(app.get('port'),function(){
	console.log('Express server listening on port '+server.address().port);
});